# Generated by Django 6.0.2 on 2026-03-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_end_date_post_stakeholders_post_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
